name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Build
        run: cargo build --all

      - name: Run tests
        run: cargo test --all

      - name: Run clippy
        run: cargo clippy --all -- -D warnings

      - name: Format check
        run: cargo fmt --all -- --check